import Head from 'next/head'
import { useState } from 'react'

const CoverLetterResponse = (props) => {
    const [isCopied, setIsCopied] = useState(false)
    let coverLetter = props.value;

    const copyToClipboard = () => {
        navigator.clipboard.writeText(coverLetter)
        setIsCopied(true)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
            <div>
                <div>
                    <h2>Generated Cover Letter:</h2>
                    <p>{coverLetter}</p>
                </div>
                <button onClick={copyToClipboard} disabled={isCopied}>
                    {isCopied ? 'Copied!' : 'Copy to Clipboard'}
                </button>
            </div>
            </main>
        </>
    )
}

export default CoverLetterResponse;