import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import FormComponent from '@/components/form'
import QuestionsComponent from '@/components/questions'

const inter = Inter({ subsets: ['latin'] })

export default function QuestionsPage() {
  return (
    <>
      <Head>
        <title>Questions </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
        <QuestionsComponent/>
      </main>
    </>
  )
}
